# Generated by Django 4.2.1 on 2023-06-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_description_en_product_description_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_en',
            new_name='description_en_us',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_en',
            new_name='title_en_us',
        ),
    ]
